# -*- coding: utf-8 -*-
"""dynamic_range_average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/arslanmit/67d73d207fa159d71f5f73bd25a7ae5d/dynamic_range_average.ipynb
"""

import pandas as pd
import os

dynamic_range=int(input('geriye donuk kac ayin ortalmasi goremek istiyorsun?'))

# Load the Excel file
file_path = '/content/sample_data/sp500_raw_data.xlsx'
data_df = pd.read_excel(file_path, sheet_name='Sheet1')
data_df.sort_values(by='date', inplace=True)
#print(data_df.head(10))
#print(data_df.iloc[:10, [0, 1, 2] ])
#print(data_df[['date','open']].head((dynamic_range+5)))

# Calculate moving average for 'open'
data_df['Moving_Average'] = data_df['open'].rolling(window=dynamic_range).mean()
#print(data_df[['date','open','Moving_Average']].head((dynamic_range+5)))

# Calculate conditon
#data_df.loc[data_df['Moving_Average'] > data_df['open'], 'conditon'] = 1
data_df['condition'] = (data_df['Moving_Average'] > data_df['open']).astype(int)

#data_df['conditon'] = data_df['open'].rolling(window=dynamic_range).mean()
#print(data_df[['date','open','Moving_Average','condition']])

filtered_df = data_df[data_df['condition']==1]
print(filtered_df[['date','open','Moving_Average','condition']])



# Calculate percentage change in 'open' column
#data_df['Percentage_Change'] = data_df['open'].pct_change()



# Create the directory if it doesn't exist
output_dir = os.path.dirname(output_file)  # Get the directory path
os.makedirs(output_dir, exist_ok=True)    # Create the directory

# Save the processed data to a new Excel file

#output_file = '/content/sample_data/processed_data.xlsx'
#data_df.to_excel(output_file, index=False)

#print(f"Processed data saved to: {output_file}")



